# SPDX-FileCopyrightText: Copyright (c) 2022-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

[project]
license = "Apache-2.0"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    # pycodestyle (errors)
    "E",
    # isort
    "I",
    # pyflakes
    "F",
    # pycodestyle (warnings)
    "W",
]
